version: '3.9'

services:
  # PostgreSQL database
  db:
    image: postgres:15
    container_name: magasincentral-api-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: magasinuser
      POSTGRES_PASSWORD: magasinpass
      POSTGRES_DB: magasincentraldb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magasinuser"]
      interval: 30s
      timeout: 5s
      retries: 5

  # .NET Core API
  app:
    image: ahmedsherif98/magasincentral-api:latest
    container_name: magasincentral-app-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=magasincentraldb;Username=magasinuser;Password=magasinpass"

    ports:
      - "70:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  db_data:
