// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PanierMcService.Data;

#nullable disable

namespace PanierMcService.Migrations
{
    [DbContext(typeof(PanierDbContext))]
    [Migration("20250623172008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PanierMcService.Models.LignePanier", b =>
                {
                    b.Property<int>("LignePanierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LignePanierId"));

                    b.Property<int>("PanierId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("LignePanierId");

                    b.HasIndex("PanierId");

                    b.ToTable("LignesPanier");

                    b.HasData(
                        new
                        {
                            LignePanierId = 1,
                            PanierId = 1,
                            ProduitId = 1,
                            Quantite = 2
                        },
                        new
                        {
                            LignePanierId = 2,
                            PanierId = 1,
                            ProduitId = 2,
                            Quantite = 1
                        });
                });

            modelBuilder.Entity("PanierMcService.Models.Panier", b =>
                {
                    b.Property<int>("PanierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PanierId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.HasKey("PanierId");

                    b.ToTable("Paniers");

                    b.HasData(
                        new
                        {
                            PanierId = 1,
                            ClientId = 100
                        });
                });

            modelBuilder.Entity("PanierMcService.Models.LignePanier", b =>
                {
                    b.HasOne("PanierMcService.Models.Panier", null)
                        .WithMany("Lignes")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PanierMcService.Models.Panier", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
