// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMcService.Data;

#nullable disable

namespace StockMcService.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20250619002417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMcService.Models.StockItem", b =>
                {
                    b.Property<int>("MagasinId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("MagasinId", "ProduitId");

                    b.ToTable("StockItems");

                    b.HasData(
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 1,
                            Quantite = 100
                        },
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 2,
                            Quantite = 80
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 1,
                            Quantite = 60
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 3,
                            Quantite = 90
                        },
                        new
                        {
                            MagasinId = 3,
                            ProduitId = 2,
                            Quantite = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
