// <auto-generated />
using System;
using MagasinCentral.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MagasinCentral.Migrations
{
    [DbContext(typeof(MagasinDbContext))]
    [Migration("20250606170700_AjoutDemandeReapprovisionnement")]
    partial class AjoutDemandeReapprovisionnement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MagasinCentral.Models.DemandeReapprovisionnement", b =>
                {
                    b.Property<int>("DemandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DemandeId"));

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MagasinId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteDemandee")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("DemandeId");

                    b.HasIndex("MagasinId");

                    b.HasIndex("ProduitId");

                    b.ToTable("DemandesReapprovisionnement");
                });

            modelBuilder.Entity("MagasinCentral.Models.Magasin", b =>
                {
                    b.Property<int>("MagasinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MagasinId"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MagasinId");

                    b.ToTable("Magasins");

                    b.HasData(
                        new
                        {
                            MagasinId = 1,
                            Adresse = "10 Rue Principale",
                            Nom = "Magasin Centre-Ville"
                        },
                        new
                        {
                            MagasinId = 2,
                            Adresse = "5 Avenue des Étudiants",
                            Nom = "Magasin Université"
                        },
                        new
                        {
                            MagasinId = 3,
                            Adresse = "23 Boulevard Nord",
                            Nom = "Magasin Quartier Nord"
                        },
                        new
                        {
                            MagasinId = 4,
                            Adresse = "42 Rue du Commerce",
                            Nom = "Magasin Sud-Ouest"
                        });
                });

            modelBuilder.Entity("MagasinCentral.Models.MagasinStockProduit", b =>
                {
                    b.Property<int>("MagasinId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("MagasinId", "ProduitId");

                    b.HasIndex("ProduitId");

                    b.ToTable("MagasinStocksProduits");

                    b.HasData(
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 1,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 2,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 3,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 1,
                            ProduitId = 4,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 1,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 2,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 3,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 2,
                            ProduitId = 4,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 3,
                            ProduitId = 1,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 3,
                            ProduitId = 2,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 3,
                            ProduitId = 3,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 3,
                            ProduitId = 4,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 4,
                            ProduitId = 1,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 4,
                            ProduitId = 2,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 4,
                            ProduitId = 3,
                            Quantite = 50
                        },
                        new
                        {
                            MagasinId = 4,
                            ProduitId = 4,
                            Quantite = 50
                        });
                });

            modelBuilder.Entity("MagasinCentral.Models.Produit", b =>
                {
                    b.Property<int>("ProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProduitId"));

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric");

                    b.HasKey("ProduitId");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            ProduitId = 1,
                            Categorie = "Papeterie",
                            Nom = "Stylo",
                            Prix = 1.50m
                        },
                        new
                        {
                            ProduitId = 2,
                            Categorie = "Papeterie",
                            Nom = "Carnet",
                            Prix = 3.75m
                        },
                        new
                        {
                            ProduitId = 3,
                            Categorie = "Électronique",
                            Nom = "Clé USB 16 Go",
                            Prix = 12.00m
                        },
                        new
                        {
                            ProduitId = 4,
                            Categorie = "Électronique",
                            Nom = "Casque Audio",
                            Prix = 45.00m
                        });
                });

            modelBuilder.Entity("MagasinCentral.Models.StockCentral", b =>
                {
                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("ProduitId");

                    b.ToTable("StocksCentraux");

                    b.HasData(
                        new
                        {
                            ProduitId = 1,
                            Quantite = 200
                        },
                        new
                        {
                            ProduitId = 2,
                            Quantite = 200
                        },
                        new
                        {
                            ProduitId = 3,
                            Quantite = 200
                        },
                        new
                        {
                            ProduitId = 4,
                            Quantite = 200
                        });
                });

            modelBuilder.Entity("MagasinCentral.Models.Vente", b =>
                {
                    b.Property<int>("VenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenteId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MagasinId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("VenteId");

                    b.HasIndex("MagasinId");

                    b.HasIndex("ProduitId");

                    b.ToTable("Ventes");

                    b.HasData(
                        new
                        {
                            VenteId = 1,
                            Date = new DateTime(2025, 6, 4, 17, 7, 0, 100, DateTimeKind.Utc).AddTicks(9013),
                            MagasinId = 1,
                            PrixUnitaire = 1.50m,
                            ProduitId = 1,
                            Quantite = 10
                        },
                        new
                        {
                            VenteId = 2,
                            Date = new DateTime(2025, 6, 5, 17, 7, 0, 100, DateTimeKind.Utc).AddTicks(9020),
                            MagasinId = 2,
                            PrixUnitaire = 12.00m,
                            ProduitId = 3,
                            Quantite = 5
                        },
                        new
                        {
                            VenteId = 3,
                            Date = new DateTime(2025, 6, 5, 17, 7, 0, 100, DateTimeKind.Utc).AddTicks(9022),
                            MagasinId = 1,
                            PrixUnitaire = 3.75m,
                            ProduitId = 2,
                            Quantite = 7
                        },
                        new
                        {
                            VenteId = 4,
                            Date = new DateTime(2025, 6, 6, 17, 7, 0, 100, DateTimeKind.Utc).AddTicks(9023),
                            MagasinId = 3,
                            PrixUnitaire = 45.00m,
                            ProduitId = 4,
                            Quantite = 2
                        });
                });

            modelBuilder.Entity("MagasinCentral.Models.DemandeReapprovisionnement", b =>
                {
                    b.HasOne("MagasinCentral.Models.Magasin", "Magasin")
                        .WithMany("DemandesReapprovisionnement")
                        .HasForeignKey("MagasinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagasinCentral.Models.Produit", "Produit")
                        .WithMany("DemandesReapprovisionnement")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magasin");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("MagasinCentral.Models.MagasinStockProduit", b =>
                {
                    b.HasOne("MagasinCentral.Models.Magasin", "Magasin")
                        .WithMany("StocksProduits")
                        .HasForeignKey("MagasinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagasinCentral.Models.Produit", "Produit")
                        .WithMany("StocksMagasin")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magasin");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("MagasinCentral.Models.StockCentral", b =>
                {
                    b.HasOne("MagasinCentral.Models.Produit", "Produit")
                        .WithOne("StockCentral")
                        .HasForeignKey("MagasinCentral.Models.StockCentral", "ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("MagasinCentral.Models.Vente", b =>
                {
                    b.HasOne("MagasinCentral.Models.Magasin", "Magasin")
                        .WithMany("Ventes")
                        .HasForeignKey("MagasinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagasinCentral.Models.Produit", "Produit")
                        .WithMany("Ventes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magasin");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("MagasinCentral.Models.Magasin", b =>
                {
                    b.Navigation("DemandesReapprovisionnement");

                    b.Navigation("StocksProduits");

                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("MagasinCentral.Models.Produit", b =>
                {
                    b.Navigation("DemandesReapprovisionnement");

                    b.Navigation("StockCentral");

                    b.Navigation("StocksMagasin");

                    b.Navigation("Ventes");
                });
#pragma warning restore 612, 618
        }
    }
}
