// <auto-generated />
using MagasinMcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MagasinMcService.Migrations
{
    [DbContext(typeof(MagasinDbContext))]
    [Migration("20250622143432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MagasinMcService.Magasin", b =>
                {
                    b.Property<int>("MagasinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MagasinId"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MagasinId");

                    b.ToTable("Magasins");

                    b.HasData(
                        new
                        {
                            MagasinId = 1,
                            Adresse = "123 Rue Principale",
                            Nom = "Magasin A"
                        },
                        new
                        {
                            MagasinId = 2,
                            Adresse = "456 Avenue Centrale",
                            Nom = "Magasin B"
                        },
                        new
                        {
                            MagasinId = 3,
                            Adresse = "789 Boulevard Sud",
                            Nom = "Magasin C"
                        },
                        new
                        {
                            MagasinId = 4,
                            Adresse = "321 Rue Nord",
                            Nom = "Magasin D"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
