// <auto-generated />
using ClientMcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClientMcService.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    partial class ClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClientMcService.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Adresse = "",
                            Courriel = "alice@dupont.ca",
                            Nom = "Alice Dupont"
                        },
                        new
                        {
                            ClientId = 2,
                            Adresse = "",
                            Courriel = "alex@alexandre.ca",
                            Nom = "Alex Alexandre"
                        },
                        new
                        {
                            ClientId = 3,
                            Adresse = "",
                            Courriel = "chris@christopher.ca",
                            Nom = "Chris Christopher"
                        },
                        new
                        {
                            ClientId = 4,
                            Adresse = "",
                            Courriel = "simon@samuel.ca",
                            Nom = "Simon Samuel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
